
const posts=window.BLOG_POSTS||[],pageSize=9;
let state={query:"",category:"All",page:1};
const grid=document.querySelector("#blog-grid"),filters=document.querySelector("#filters"),search=document.querySelector("#search"),pagination=document.querySelector("#pagination"),count=document.querySelector("#result-count");
const categories=["All",...new Set(posts.map(p=>p.category))];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function renderFilters(){filters.innerHTML=categories.map(c=>`<button class="filter ${c===state.category?"active":""}" data-category="${esc(c)}">${esc(c)}</button>`).join("");filters.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{state.category=b.dataset.category;state.page=1;render()})}
function filtered(){const q=state.query.trim().toLowerCase();return posts.filter(p=>{const cat=state.category==="All"||p.category===state.category;const hay=[p.title,p.excerpt,p.category,...p.tags].join(" ").toLowerCase();return cat&&(!q||hay.includes(q))}).sort((a,b)=>b.date.localeCompare(a.date))}
function render(){const all=filtered(),pages=Math.max(1,Math.ceil(all.length/pageSize));state.page=Math.min(state.page,pages);const visible=all.slice((state.page-1)*pageSize,state.page*pageSize);count.textContent=`${all.length} article${all.length===1?"":"s"}`;grid.innerHTML=visible.length?visible.map(p=>`<a class="card" href="${esc(p.url)}"><div class="card-meta">${esc(p.category)} · ${esc(p.date)} · ${p.readingTime} min read</div><h2>${esc(p.title)}</h2><p>${esc(p.excerpt)}</p><div class="tag-row">${p.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join("")}</div></a>`).join(""):`<div class="empty">No articles match your search.</div>`;pagination.innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${i+1===state.page?"active":""}" data-page="${i+1}">${i+1}</button>`).join("");pagination.querySelectorAll(".page-btn").forEach(b=>b.onclick=()=>{state.page=+b.dataset.page;render();scrollTo({top:document.querySelector(".blog-controls").offsetTop-80,behavior:"smooth"})})}
search.oninput=e=>{state.query=e.target.value;state.page=1;render()};renderFilters();render();
